version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - authenticated
      - organization
    networks:
      - factify-network

  authenticated:
    build:
      context: ./authenticated
    ports:
      - "3000:3000"
    networks:
      - factify-network
  
  organization:
    build:
      context: ./organization
    ports:
      - "3001:3000"
    networks:
      - factify-network

networks:
  factify-network:
    driver: bridge
