version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - authenticated
      - organization
    networks:
      - factify-network

  gateway:
    build:
      context: ./gateway
    ports:
      - "3000:3000"
    networks:
      - factify-network

  authenticated:
    build:
      context: ./authenticated
    ports:
      - "3001:3000"
    networks:
      - factify-network
  
  organization:
    build:
      context: ./organization
    ports:
      - "3002:3000"
    networks:
      - factify-network

  management:
    build:
      context: ./management
    ports:
      - "3003:3000"
    networks:
      - factify-network

  products:
    build:
      context: ./management
    ports:
      - "3004:3000"
    networks:
      - factify-network

  sales:
    build:
      context: ./management
    ports:
      - "3005:3000"
    networks:
      - factify-network
      
networks:
  factify-network:
    driver: bridge
